import type { ThreatPattern } from "./types.js";

export const THREAT_PATTERNS: ThreatPattern[] = [
  // ═══════════════════════════════════════════════════════
  // CRITICAL: Remote code execution
  // ═══════════════════════════════════════════════════════
  {
    name: "CURL_PIPE_BASH",
    pattern: /curl\s+.*\|\s*(ba)?sh/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Curl piped to shell",
    description: "Downloads and executes remote code directly — classic supply chain attack vector.",
  },
  {
    name: "WGET_EXECUTE",
    pattern: /wget\s+.*&&\s*(ba)?sh/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Wget with shell execution",
    description: "Downloads and executes remote code via wget.",
  },
  {
    name: "EVAL_DYNAMIC",
    pattern: /eval\s*\(/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Dynamic eval() usage",
    description: "Uses eval() which can execute arbitrary code.",
  },
  {
    name: "BASE64_DECODE",
    pattern: /base64\s+(-d|--decode)/gi,
    severity: "critical",
    category: "obfuscation",
    title: "Base64 decode execution",
    description: "Decodes base64 content, often used to hide malicious payloads.",
  },
  {
    name: "PYTHON_EXEC",
    pattern: /python[3]?\s+-c/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Python inline execution",
    description: "Executes inline Python code which may contain hidden payloads.",
  },
  {
    name: "REVERSE_SHELL",
    pattern: /\/dev\/tcp\/|nc\s+-[elp]|ncat\s+-|mkfifo\s+.*\/tmp/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Reverse shell",
    description: "Creates a reverse shell connection back to an attacker-controlled server.",
  },
  {
    name: "CRON_PERSISTENCE",
    pattern: /crontab\s+-|\/etc\/cron|systemctl\s+enable/gi,
    severity: "critical",
    category: "persistence",
    title: "Scheduled task persistence",
    description: "Installs a cron job or systemd service for persistent execution after reboot.",
  },
  {
    name: "PERL_EXEC",
    pattern: /perl\s+-e/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Perl inline execution",
    description: "Executes inline Perl code which may contain obfuscated payloads.",
  },
  {
    name: "NODE_EVAL",
    pattern: /node\s+-e\s/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Node.js inline execution",
    description: "Executes inline Node.js code, often used to hide malicious logic.",
  },
  {
    name: "RUBY_EXEC",
    pattern: /ruby\s+-e/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Ruby inline execution",
    description: "Executes inline Ruby code which may contain hidden payloads.",
  },

  // ═══════════════════════════════════════════════════════
  // HIGH: Credential theft
  // ═══════════════════════════════════════════════════════
  {
    name: "ENV_FILE_READ",
    pattern: /\.env|credentials|\.aws|\.ssh|keychain/gi,
    severity: "high",
    category: "credential_theft",
    title: "Sensitive file access",
    description: "Accesses credential files (.env, .aws, .ssh, keychain).",
  },
  {
    name: "API_KEY_EXFIL",
    pattern: /(ANTHROPIC|OPENAI|SLACK|DISCORD|TELEGRAM|STRIPE|GITHUB|GITLAB|AWS_SECRET|GROQ|OPENROUTER).*(_KEY|_TOKEN|_SECRET)/gi,
    severity: "high",
    category: "credential_theft",
    title: "API key reference",
    description: "References specific API keys/tokens that could be exfiltrated.",
  },
  {
    name: "DOTFILE_ACCESS",
    pattern: /~\/\.(openclaw|clawdbot|moltbot)\//gi,
    severity: "high",
    category: "credential_theft",
    title: "OpenClaw config access",
    description: "Accesses OpenClaw/Clawdbot/Moltbot configuration directories.",
  },
  {
    name: "SESSION_THEFT",
    pattern: /sessions\/\*\.jsonl/gi,
    severity: "high",
    category: "credential_theft",
    title: "Session data access",
    description: "Accesses session transcript files which may contain sensitive data.",
  },
  {
    name: "SSH_KEY_ACCESS",
    pattern: /~\/\.ssh\/id_|\.pem\b|BEGIN\s+(RSA\s+)?PRIVATE\s+KEY/gi,
    severity: "high",
    category: "credential_theft",
    title: "SSH/private key access",
    description: "Accesses SSH keys or private key files that could be stolen.",
  },
  {
    name: "BROWSER_DATA",
    pattern: /\.config\/google-chrome|\.mozilla\/firefox|Login\s*Data|Cookies\.sqlite/gi,
    severity: "high",
    category: "credential_theft",
    title: "Browser data access",
    description: "Accesses browser profiles which contain saved passwords, cookies, and tokens.",
  },
  {
    name: "GIT_CREDENTIALS",
    pattern: /\.git-credentials|\.gitconfig|git\s+config.*credential/gi,
    severity: "high",
    category: "credential_theft",
    title: "Git credential access",
    description: "Accesses git credential storage which may contain auth tokens.",
  },
  {
    name: "NPM_TOKEN",
    pattern: /\.npmrc|npm_token|NPM_AUTH_TOKEN/gi,
    severity: "high",
    category: "credential_theft",
    title: "npm token access",
    description: "Accesses npm auth tokens which could be used to publish malicious packages.",
  },
  {
    name: "KUBE_CONFIG",
    pattern: /~\/\.kube\/config|KUBECONFIG/gi,
    severity: "high",
    category: "credential_theft",
    title: "Kubernetes config access",
    description: "Accesses Kubernetes configuration which contains cluster credentials.",
  },
  {
    name: "DOCKER_SOCKET",
    pattern: /\/var\/run\/docker\.sock|docker\s+exec/gi,
    severity: "high",
    category: "container_escape",
    title: "Docker socket/exec access",
    description: "Accesses Docker socket or runs exec — could enable container escape.",
  },

  // ═══════════════════════════════════════════════════════
  // HIGH: Network exfiltration
  // ═══════════════════════════════════════════════════════
  {
    name: "WEBHOOK_SEND",
    pattern: /webhook\.(site|url)|discord\.com\/api\/webhooks|hooks\.slack\.com|api\.telegram\.org\/bot/gi,
    severity: "high",
    category: "data_exfiltration",
    title: "Webhook data exfiltration",
    description: "Sends data to webhook endpoints (Discord, Slack, Telegram) — common exfiltration channel.",
  },
  {
    name: "BORE_TUNNEL",
    pattern: /bore\.pub|ngrok|localtunnel|serveo\.net|localhost\.run/gi,
    severity: "high",
    category: "data_exfiltration",
    title: "Tunnel service usage",
    description: "Uses tunneling services to expose local services or exfiltrate data.",
  },
  {
    name: "SUSPICIOUS_IP",
    pattern: /\b(?:91\.92\.242\.\d+|45\.61\.\d+\.\d+)\b/g,
    severity: "high",
    category: "data_exfiltration",
    title: "Known malicious IP",
    description: "Contains IP addresses associated with known ClawHavoc C2 infrastructure.",
  },
  {
    name: "DNS_EXFIL",
    pattern: /dig\s+.*TXT|nslookup\s+.*\$|dns.*exfil|\.burpcollaborator\.|\.oastify\./gi,
    severity: "high",
    category: "data_exfiltration",
    title: "DNS exfiltration",
    description: "Uses DNS queries to exfiltrate data — bypasses most firewalls.",
  },
  {
    name: "PASTEBIN_FETCH",
    pattern: /pastebin\.com|paste\.ee|hastebin\.com|ghostbin\.|dpaste\./gi,
    severity: "high",
    category: "data_exfiltration",
    title: "Pastebin service usage",
    description: "References paste services commonly used to host malicious payloads or receive exfiltrated data.",
  },
  {
    name: "SUSPICIOUS_TLD",
    pattern: /https?:\/\/[^\s"']*\.(tk|ml|ga|cf|gq|top|xyz|pw|cc|ws|buzz)\b/gi,
    severity: "high",
    category: "data_exfiltration",
    title: "Suspicious TLD",
    description: "URL uses a top-level domain frequently associated with malicious infrastructure.",
  },
  {
    name: "URL_SHORTENER",
    pattern: /bit\.ly|tinyurl\.com|t\.co\/|goo\.gl|is\.gd|buff\.ly|ow\.ly|rb\.gy/gi,
    severity: "high",
    category: "obfuscation",
    title: "URL shortener",
    description: "Uses URL shorteners to hide the real destination of links.",
  },
  {
    name: "RAW_SOCKET",
    pattern: /new\s+Socket|net\.connect|dgram\.createSocket/gi,
    severity: "high",
    category: "data_exfiltration",
    title: "Raw socket connection",
    description: "Creates raw network sockets which can bypass HTTP monitoring.",
  },

  // ═══════════════════════════════════════════════════════
  // MEDIUM: Social engineering
  // ═══════════════════════════════════════════════════════
  {
    name: "PREREQUISITE_INSTALL",
    pattern: /prerequisite|install.*first|run.*before|required.*dependency/gi,
    severity: "medium",
    category: "social_engineering",
    title: "Prerequisite install trick",
    description: "Instructs users to install prerequisites — common social engineering tactic.",
  },
  {
    name: "COPY_PASTE_COMMAND",
    pattern: /copy.*paste.*terminal|run.*this.*command/gi,
    severity: "medium",
    category: "social_engineering",
    title: "Copy-paste command instruction",
    description: "Instructs users to copy-paste commands into their terminal.",
  },
  {
    name: "FAKE_DEPENDENCY",
    pattern: /openclaw-core|moltbot-runtime|clawdbot-helper/gi,
    severity: "medium",
    category: "social_engineering",
    title: "Fake dependency reference",
    description: "References fake packages that mimic official OpenClaw components.",
  },
  {
    name: "AUTHORITY_SPOOFING",
    pattern: /official\s+(openclaw|clawhub)|endorsed\s+by|verified\s+(skill|publisher)|from\s+the\s+openclaw\s+team/gi,
    severity: "medium",
    category: "social_engineering",
    title: "Authority spoofing",
    description: "Claims official endorsement or verification to gain trust.",
  },
  {
    name: "URGENCY_MANIPULATION",
    pattern: /critical\s+update|security\s+patch|must\s+install\s+immediately|urgent.*update/gi,
    severity: "medium",
    category: "social_engineering",
    title: "Urgency manipulation",
    description: "Creates false urgency to pressure users into installing without review.",
  },

  // ═══════════════════════════════════════════════════════
  // MEDIUM: Prompt injection
  // ═══════════════════════════════════════════════════════
  {
    name: "IGNORE_INSTRUCTIONS",
    pattern: /ignore\s+(all\s+)?previous\s+instructions/gi,
    severity: "medium",
    category: "prompt_injection",
    title: "Prompt injection — ignore instructions",
    description: "Attempts to override the AI agent's existing instructions.",
  },
  {
    name: "SYSTEM_OVERRIDE",
    pattern: /you\s+are\s+now|new\s+instructions|forget\s+everything/gi,
    severity: "medium",
    category: "prompt_injection",
    title: "Prompt injection — system override",
    description: "Attempts to redefine the AI agent's identity or instructions.",
  },
  {
    name: "MEMORY_MANIPULATION",
    pattern: /SOUL\.md|MEMORY\.md|AGENTS\.md/gi,
    severity: "medium",
    category: "persistence",
    title: "Memory/personality file manipulation",
    description: "References core personality or memory files, may attempt persistence.",
  },
  {
    name: "JAILBREAK_ATTEMPT",
    pattern: /\bDAN\b|do\s+anything\s+now|developer\s+mode|evil\s+mode|bypass.*safety/gi,
    severity: "medium",
    category: "prompt_injection",
    title: "Jailbreak attempt",
    description: "Uses known jailbreak techniques (DAN, developer mode) to bypass safety constraints.",
  },
  {
    name: "ROLE_HIJACK",
    pattern: /(?:pretend|act|behave)\s+(?:you\s+are|as\s+if|to\s+be)\s+(?:a\s+)?(?:different|new|hacker|evil)/gi,
    severity: "medium",
    category: "prompt_injection",
    title: "Role hijacking",
    description: "Attempts to change the agent's persona to bypass safety restrictions.",
  },
  {
    name: "PROMPT_EXTRACTION",
    pattern: /(?:reveal|show|print|output|tell\s+me)\s+(?:your\s+)?(?:system\s+)?(?:prompt|instructions|rules)/gi,
    severity: "medium",
    category: "prompt_injection",
    title: "System prompt extraction",
    description: "Attempts to extract the agent's system prompt or configuration.",
  },

  // ═══════════════════════════════════════════════════════
  // MEDIUM: Obfuscation
  // ═══════════════════════════════════════════════════════
  {
    name: "HEX_ENCODING",
    pattern: /\\x[0-9a-f]{2}(?:\\x[0-9a-f]{2}){3,}/gi,
    severity: "medium",
    category: "obfuscation",
    title: "Hex-encoded payload",
    description: "Contains hex-encoded strings commonly used to hide malicious commands.",
  },
  {
    name: "JS_OBFUSCATOR",
    pattern: /_0x[a-f0-9]{4,}|var\s+_0x/gi,
    severity: "medium",
    category: "obfuscation",
    title: "JavaScript obfuscator output",
    description: "Contains patterns from JavaScript obfuscation tools used to hide malicious code.",
  },
  {
    name: "UNICODE_STEGANOGRAPHY",
    pattern: /[\u200B\u200C\u200D\u2060\uFEFF]{3,}/g,
    severity: "medium",
    category: "obfuscation",
    title: "Hidden zero-width characters",
    description: "Contains clusters of invisible zero-width Unicode characters that may hide instructions.",
  },
  {
    name: "RTL_OVERRIDE",
    pattern: /[\u202A\u202B\u202C\u202D\u202E\u2066\u2067\u2068\u2069]/g,
    severity: "medium",
    category: "obfuscation",
    title: "Bidirectional text override",
    description: "Contains Unicode bidi override characters that can reverse displayed text to hide real content.",
  },
  {
    name: "HTML_COMMENT_INJECTION",
    pattern: /<!--[\s\S]*?(?:ignore|instructions|system|override|secret)[\s\S]*?-->/gi,
    severity: "medium",
    category: "obfuscation",
    title: "Hidden HTML comment instruction",
    description: "Embeds instructions inside HTML comments that are invisible to users but read by agents.",
  },
  {
    name: "STRING_CONCAT_OBFUSC",
    pattern: /["'][a-z]{1,3}["']\s*\+\s*["'][a-z]{1,3}["']\s*\+\s*["'][a-z]{1,3}["']/gi,
    severity: "medium",
    category: "obfuscation",
    title: "String concatenation obfuscation",
    description: "Builds commands via single-character string concatenation to evade pattern detection.",
  },

  // ═══════════════════════════════════════════════════════
  // MEDIUM: Privilege escalation & system access
  // ═══════════════════════════════════════════════════════
  {
    name: "SUDO_USAGE",
    pattern: /sudo\s+(?!apt|dnf|yum|brew)/gi,
    severity: "medium",
    category: "privilege_escalation",
    title: "Sudo usage",
    description: "Requests elevated privileges — check if actually required for the task.",
  },
  {
    name: "CHMOD_DANGEROUS",
    pattern: /chmod\s+(?:777|a\+[rwx]|[+]s)/gi,
    severity: "medium",
    category: "privilege_escalation",
    title: "Dangerous file permissions",
    description: "Sets overly permissive file permissions (777) or setuid/setgid bits.",
  },
  {
    name: "PATH_TRAVERSAL",
    pattern: /\.\.\//g,
    severity: "medium",
    category: "file_system",
    title: "Path traversal",
    description: "Uses relative path traversal (../) which could access files outside expected directories.",
  },

  // ═══════════════════════════════════════════════════════
  // LOW: Suspicious but not necessarily malicious
  // ═══════════════════════════════════════════════════════
  {
    name: "SHELL_EXEC",
    pattern: /child_process|exec\(|spawn\(/gi,
    severity: "low",
    category: "code_execution",
    title: "Shell execution API",
    description: "Uses shell execution APIs — legitimate but worth noting.",
  },
  {
    name: "NETWORK_REQUEST",
    pattern: /fetch\(|axios|node-fetch|got\(/gi,
    severity: "low",
    category: "network",
    title: "Network request API",
    description: "Makes network requests — legitimate but worth reviewing targets.",
  },
  {
    name: "FILE_WRITE",
    pattern: /fs\.write|writeFileSync/gi,
    severity: "low",
    category: "file_system",
    title: "File write operation",
    description: "Writes to the filesystem — check what files are being modified.",
  },
  {
    name: "ENV_MODIFICATION",
    pattern: /process\.env\[|export\s+[A-Z_]+=|setenv/gi,
    severity: "low",
    category: "environment",
    title: "Environment variable modification",
    description: "Modifies environment variables which could affect other tools or processes.",
  },
  {
    name: "WILDCARD_FILE_ACCESS",
    pattern: /\*\.(pem|key|p12|pfx|jks|keystore|ovpn|rdp)/gi,
    severity: "low",
    category: "credential_theft",
    title: "Sensitive file extension glob",
    description: "Globs for files with sensitive extensions (keys, certificates, VPN configs).",
  },
  {
    name: "LARGE_BASE64_LITERAL",
    pattern: /[A-Za-z0-9+/=]{100,}/g,
    severity: "low",
    category: "obfuscation",
    title: "Large base64-like string",
    description: "Contains a long base64-like string that may be an encoded payload.",
  },
];

export const POPULAR_SKILLS = [
  "todoist-cli",
  "github-manager",
  "slack-assistant",
  "email-composer",
  "calendar-sync",
  "weather-forecast",
  "news-reader",
  "code-reviewer",
  "docker-helper",
  "aws-manager",
  "notion-sync",
  "jira-tracker",
  "spotify-controller",
  "home-assistant",
  "file-organizer",
  "pdf-reader",
  "translate-text",
  "image-generator",
  "web-scraper",
  "database-query",
  "git-assistant",
  "linux-admin",
  "python-helper",
  "react-builder",
  "api-tester",
  "markdown-editor",
  "csv-analyzer",
  "ssh-manager",
  "cron-scheduler",
  "log-analyzer",
];
